// sdk/src/adapters/svelte/components/Selection.svelte
<script lang="ts">
  /**
   * Selection component for rendering a single user's text selection
   * @module adapters/svelte/components/Selection
   */

  import { deserializeRange } from '../../../cursor/selection'
  import type { SerializedRange, SelectionRange, CursorMode } from '../../../cursor/types'
  import type { Writable } from 'svelte/store'
  import type { SelectionUser } from '../types/selection'

  /**
   * Type guard to check if selection is in new serialized format
   */
  function isSerializedRange(selection: any): selection is SerializedRange {
    return selection &&
           typeof selection.startXPath === 'string' &&
           typeof selection.startOffset === 'number' &&
           typeof selection.endXPath === 'string' &&
           typeof selection.endOffset === 'number'
  }

  /**
   * Type guard to check if selection is in old visual format
   */
  function isVisualRange(selection: any): selection is SelectionRange {
    return selection && Array.isArray(selection.rects)
  }

  interface Props {
    /** User whose selection to render */
    user: SelectionUser
    /** Positioning mode (viewport or container) */
    mode?: CursorMode
    /** Container store (required for container mode) */
    containerRef?: Writable<HTMLElement | null>
    /** Selection box opacity (default: 0.2) */
    opacity?: number
  }

  let {
    user,
    mode = 'viewport',
    containerRef = undefined,
    opacity = 0.2
  }: Props = $props()

  // Convert selection to visual format
  // Supports both new semantic format and old visual format for backward compatibility
  let visualSelection = $derived.by(() => {
    if (!user.selection) return null

    // New format (SerializedRange): Deserialize to visual coordinates
    if (isSerializedRange(user.selection)) {
      // containerRef is passed as a Writable store, don't dereference it here
      // deserializeRange will handle it appropriately
      return deserializeRange(
        user.selection,
        mode,
        undefined
      )
    }

    // Old format (SelectionRange): Use directly
    // This path provides backward compatibility for existing implementations
    if (isVisualRange(user.selection)) {
      console.warn(
        '[Selection] Received deprecated visual selection format. ' +
        'Please upgrade to semantic selection for cross-layout compatibility.'
      )
      return user.selection
    }

    return null
  })

  // Don't render if conversion failed or no rectangles
  let shouldRender = $derived.by(() => {
    if (!visualSelection || visualSelection.rects.length === 0) {
      return false
    }

    // Validate container mode requirements (check if containerRef has a value if it's a store)
    if (mode === 'container') {
      const hasContainer = containerRef ?
        (typeof (containerRef as any).subscribe === 'function' ? true : !!containerRef) :
        false
      if (!hasContainer) {
        console.warn('[Selection] Container mode requires containerRef')
        return false
      }
    }

    return true
  })

  let color = $derived(user.color || '#3b82f6')
</script>

{#if shouldRender && visualSelection}
  {#each visualSelection.rects as rect}
    <div
      data-selection-id={user.id}
      data-user-name={user.name}
      style:position={mode === 'container' ? 'absolute' : 'fixed'}
      style:left="0"
      style:top="0"
      style:transform="translate({rect.x}px, {rect.y}px)"
      style:width="{rect.width}px"
      style:height="{rect.height}px"
      style:background-color={color}
      style:opacity={opacity}
      style:pointer-events="none"
      style:z-index="9998"
      style:transition="opacity 0.2s ease"
      style:border-radius="2px"
    ></div>
  {/each}
{/if}

// sdk/src/adapters/react/Selection.tsx
/**
 * Selection component for rendering a single user's text selection
 * @module adapters/react/Selection
 */

import type { ReactNode } from 'react'
import type { SelectionRange, CursorMode } from '../../cursor/types'

/**
 * User with selection data
 */
export interface SelectionUser {
  /** Unique user/client ID */
  id: string
  /** User name (for label) */
  name?: string
  /** User color (for highlight) */
  color?: string
  /** Selection range (multiple rectangles for multi-line) */
  selection?: SelectionRange | null
}

/**
 * Props for Selection component
 */
export interface SelectionProps {
  /** User whose selection to render */
  user: SelectionUser

  /** Positioning mode (viewport or container) */
  mode?: CursorMode

  /** Container ref (required for container mode) */
  containerRef?: React.RefObject<HTMLElement>

  /** Selection box opacity (default: 0.2) */
  opacity?: number
}

/**
 * Selection component - renders a single user's text selection as highlight boxes
 *
 * Renders each line of a multi-line selection as a separate rectangle,
 * similar to Google Docs selection visualization.
 *
 * @param props - Component props
 * @returns React element or null if no selection
 *
 * @example
 * ```tsx
 * <Selection
 *   user={user}
 *   mode="container"
 *   containerRef={editorRef}
 *   opacity={0.2}
 * />
 * ```
 */
export function Selection({
  user,
  mode = 'viewport',
  containerRef,
  opacity = 0.2
}: SelectionProps): ReactNode {
  // Don't render if no selection
  if (!user.selection || user.selection.rects.length === 0) {
    return null
  }

  // Validate container mode requirements
  if (mode === 'container' && !containerRef?.current) {
    console.warn('[Selection] Container mode requires containerRef')
    return null
  }

  const color = user.color || '#3b82f6'

  return (
    <>
      {user.selection.rects.map((rect, index) => (
        <div
          key={`${user.id}-rect-${index}`}
          data-selection-id={user.id}
          data-user-name={user.name}
          style={{
            position: mode === 'container' ? 'absolute' : 'fixed',
            left: 0,
            top: 0,
            transform: `translate(${rect.x}px, ${rect.y}px)`,
            width: `${rect.width}px`,
            height: `${rect.height}px`,
            backgroundColor: color,
            opacity,
            pointerEvents: 'none',
            zIndex: 9998, // Below cursors (9999) but above content
            transition: 'opacity 0.2s ease',
            borderRadius: '2px'
          }}
        />
      ))}
    </>
  )
}
